--
-- TOC entry 219 (class 1259 OID 16694)
-- Name: compatibilidade_produto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.compatibilidade_produto (
    id bigint NOT NULL,
    ano_final integer NOT NULL,
    ano_inicial integer NOT NULL,
    modelo_id bigint NOT NULL,
    produto_id bigint NOT NULL
);



--
-- TOC entry 218 (class 1259 OID 16693)
-- Name: compatibilidade_produto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.compatibilidade_produto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compatibilidade_produto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--
-- TOC entry 221 (class 1259 OID 16700)
-- Name: marca; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.marca (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    atualizado_em timestamp(6) without time zone,
    criado_em timestamp(6) without time zone,
    nome character varying(255) NOT NULL
);



--
-- TOC entry 220 (class 1259 OID 16699)
-- Name: marca_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.marca ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marca_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--
-- TOC entry 223 (class 1259 OID 16706)
-- Name: modelo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.modelo (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    atualizado_em timestamp(6) without time zone,
    criado_em timestamp(6) without time zone,
    nome character varying(255) NOT NULL,
    marca_id bigint NOT NULL
);



--
-- TOC entry 222 (class 1259 OID 16705)
-- Name: modelo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.modelo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.modelo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--
-- TOC entry 225 (class 1259 OID 16712)
-- Name: produto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.produto (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    atualizado_em timestamp(6) without time zone,
    criado_em timestamp(6) without time zone,
    descricao character varying(255),
    estoque integer NOT NULL,
    nome character varying(255) NOT NULL,
    preco numeric(10,2) NOT NULL
);



--
-- TOC entry 227 (class 1259 OID 16720)
-- Name: produto_foto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.produto_foto (
    id bigint NOT NULL,
    destaque boolean NOT NULL,
    public_id character varying(255) NOT NULL,
    url character varying(255) NOT NULL,
    produto_id bigint NOT NULL
);



--
-- TOC entry 226 (class 1259 OID 16719)
-- Name: produto_foto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.produto_foto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produto_foto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--
-- TOC entry 224 (class 1259 OID 16711)
-- Name: produto_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.produto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--
-- TOC entry 230 (class 1259 OID 24671)
-- Name: site_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.site_settings (
    id bigint NOT NULL,
    whatsapp_phone character varying(32),
    about_html text,
    updated_at timestamp without time zone
);



--
-- TOC entry 229 (class 1259 OID 16728)
-- Name: usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    CONSTRAINT usuario_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying])::text[])))
);



--
-- TOC entry 228 (class 1259 OID 16727)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--
-- TOC entry 4781 (class 2606 OID 16698)
-- Name: compatibilidade_produto compatibilidade_produto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.compatibilidade_produto
    ADD CONSTRAINT compatibilidade_produto_pkey PRIMARY KEY (id);



--
-- TOC entry 4783 (class 2606 OID 16704)
-- Name: marca marca_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marca
    ADD CONSTRAINT marca_pkey PRIMARY KEY (id);



--
-- TOC entry 4787 (class 2606 OID 16710)
-- Name: modelo modelo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.modelo
    ADD CONSTRAINT modelo_pkey PRIMARY KEY (id);



--
-- TOC entry 4793 (class 2606 OID 16726)
-- Name: produto_foto produto_foto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produto_foto
    ADD CONSTRAINT produto_foto_pkey PRIMARY KEY (id);



--
-- TOC entry 4791 (class 2606 OID 16718)
-- Name: produto produto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT produto_pkey PRIMARY KEY (id);



--
-- TOC entry 4799 (class 2606 OID 24677)
-- Name: site_settings site_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.site_settings
    ADD CONSTRAINT site_settings_pkey PRIMARY KEY (id);



--
-- TOC entry 4795 (class 2606 OID 16741)
-- Name: usuario uk863n1y3x0jalatoir4325ehal; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk863n1y3x0jalatoir4325ehal UNIQUE (username);



--
-- TOC entry 4789 (class 2606 OID 16739)
-- Name: modelo ukf1rpboynui4jptentrxnnkanb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.modelo
    ADD CONSTRAINT ukf1rpboynui4jptentrxnnkanb UNIQUE (nome);



--
-- TOC entry 4785 (class 2606 OID 16737)
-- Name: marca ukix7qqllivg82mpp45cgolja3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marca
    ADD CONSTRAINT ukix7qqllivg82mpp45cgolja3 UNIQUE (nome);



--
-- TOC entry 4797 (class 2606 OID 16735)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);



--
-- TOC entry 4803 (class 2606 OID 16757)
-- Name: produto_foto fk8vyooaxjnrtgld5akin4qh1tk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produto_foto
    ADD CONSTRAINT fk8vyooaxjnrtgld5akin4qh1tk FOREIGN KEY (produto_id) REFERENCES public.produto(id);



--
-- TOC entry 4802 (class 2606 OID 16752)
-- Name: modelo fkllxq2dldvhxvb5q9csar7vdfy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.modelo
    ADD CONSTRAINT fkllxq2dldvhxvb5q9csar7vdfy FOREIGN KEY (marca_id) REFERENCES public.marca(id);



--
-- TOC entry 4800 (class 2606 OID 16742)
-- Name: compatibilidade_produto fktbemb0hgk1xxwufdfle1b1qbd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.compatibilidade_produto
    ADD CONSTRAINT fktbemb0hgk1xxwufdfle1b1qbd FOREIGN KEY (modelo_id) REFERENCES public.modelo(id);



--
-- TOC entry 4801 (class 2606 OID 16747)
-- Name: compatibilidade_produto fkuwvmq5g1sivs9wdmifnxcwjj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.compatibilidade_produto
    ADD CONSTRAINT fkuwvmq5g1sivs9wdmifnxcwjj FOREIGN KEY (produto_id) REFERENCES public.produto(id);
